arb-dir: lib/l10n
template-arb-file: app_ar.arb
output-localization-file: app_localizations.dart
# Place generated file directly in lib/l10n to ensure it's in build context
output-dir: lib/l10n
output-class: AppLocalizations
preferred-supported-locales: [ar]
