name: giving_bridge
description: A modern web platform for charitable giving built with Flutter Web
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^16.2.4

  # State Management
  provider: ^6.1.1

  # UI Components
  material_color_utilities: ^0.11.1

  # Responsive Design
  responsive_framework: ^1.1.1

  # Form Validation
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0

  # Icons
  font_awesome_flutter: ^10.6.0

  # Animations
  animations: ^2.0.8

  # HTTP (for future API integration)
  http: ^1.1.0

  # Shared Preferences
  shared_preferences: ^2.2.2

  # Image handling
  cached_network_image: ^3.3.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
